AWSTemplateFormatVersion: 2010-09-09
Description: GitHub OIDC for when GitHub wants to communicate with AWS.

Resources:

  # OIDC Provider definition
  GitHubActionsOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - d89e3bd43d5d909b47a18977aa9d5ce36cee184c  # Correct GitHub thumbprint
      Url: https://token.actions.githubusercontent.com

  # IAM Role for GitHub Actions
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHub_Actions_Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubActionsOidcProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': ['repo:pjv93/sample-app:*']
              StringEquals:
                'token.actions.githubusercontent.com:aud': sts.amazonaws.com

  # IAM Managed Policy for the GitHub Actions Role
  GitHubActionsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GitHub_Actions_Policy
      # Removed: Roles:
      #   - Ref: GitHubActionsRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:        
          - Sid: AllowS3Actions
            Effect: Allow
            Action:
              - s3:ListBuckets
              - s3:PutObject
            Resource:
              # Replace with your unique S3 bucket name
              - arn:aws:s3:::my-oidc-bucket-187
              - arn:aws:s3:::my-oidc-bucket-187/*

  # Policy Attachment
  GitHubActionsPolicyAttachment:
    Type: AWS::IAM::PolicyAttachment
    Properties:
      PolicyArn: !Ref GitHubActionsManagedPolicy
      Roles: 
        - !Ref GitHubActionsRole
