AWSTemplateFormatVersion: '2010-09-09'
Description: Bitbucket OIDC configuration for communication between Bitbucket and AWS.

Parameters:
  WorkspaceName:
    Type: String
    Description: Bitbucket workspace name (e.g., pjv93)
  
  RepositoryName:
    Type: String
    Description: Bitbucket repository name (e.g., sample-app)
  
  BucketName:
    Type: String
    Description: S3 bucket name (e.g., iampjv.co)
  
  IAMRoleName:
    Type: String
    Default: Bitbucket_Actions_Role
    Description: IAM role name for Bitbucket OIDC

Resources:
  # OIDC Provider definition
  BitbucketActionsOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - a031c46782e6e6c661cd4bd10397f7fdc7df0afe  # Bitbucket's OIDC thumbprint
      Url: !Sub "https://api.bitbucket.org/2.0/workspaces/${WorkspaceName}/pipelines-config/identity/oidc"

  # IAM Role for Bitbucket Actions
  BitbucketActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref IAMRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/api.bitbucket.org/2.0/workspaces/${WorkspaceName}/pipelines-config/identity/oidc"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                !Sub "api.bitbucket.org/2.0/workspaces/${WorkspaceName}/pipelines-config/identity/oidc:aud": "sts.amazonaws.com"
              StringLike:
                !Sub "api.bitbucket.org/2.0/workspaces/${WorkspaceName}/pipelines-config/identity/oidc:sub": "repository:${WorkspaceName}/${RepositoryName}:*"
      ManagedPolicyArns:
        - !Ref BitbucketActionsManagedPolicy

  # IAM Managed Policy for the Bitbucket Actions Role
  BitbucketActionsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${IAMRoleName}_Policy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # S3 bucket-level permissions
          - Sid: AllowS3Actions
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:ListBucketMultipartUploads
            Resource:
              - !Sub "arn:aws:s3:::${BucketName}"
          
          # S3 object-level permissions
          - Sid: AllowS3ObjectActions
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
            Resource:
              - !Sub "arn:aws:s3:::${BucketName}/*"
