AWSTemplateFormatVersion: '2010-09-09'
Description: Bitbucket OIDC configuration for communication between Bitbucket and AWS.

Resources:
  # OIDC Provider definition
  BitbucketActionsOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - a031c46782e6e6c661cd4bd10397f7fdc7df0afe  # Bitbucket's OIDC thumbprint
      Url: https://api.bitbucket.org/2.0/workspaces

  # IAM Role for Bitbucket Actions
  BitbucketActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Bitbucket_Actions_Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/api.bitbucket.org/2.0/workspaces"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "api.bitbucket.org/2.0/workspaces:aud": "sts.amazonaws.com"
              StringLike:
                # Updated for your repository
                "api.bitbucket.org/2.0/workspaces:sub": "repository:pjv93/sample-app:*"
      
      # Attach the managed policy to this role
      ManagedPolicyArns:
        - !Ref BitbucketActionsManagedPolicy

  # IAM Managed Policy for the Bitbucket Actions Role
  BitbucketActionsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Bitbucket_Actions_Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Example: Permissions for S3 bucket-level operations
          - Sid: AllowS3Actions
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:ListBucketMultipartUploads
            Resource:
              # Replace with your actual S3 bucket ARN
              - arn:aws:s3:::iampjv.co
          
          # Example: Permissions for S3 object-level operations
          - Sid: AllowS3ObjectActions
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
            Resource:
              # Updated for your bucket, including object-level permissions
              - arn:aws:s3:::iampjv.co/*

          # Add more permission blocks here for other AWS services as needed
          # Follow the principle of least privilege
