AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for GitLab OIDC Authentication with support for multiple namespaces and repositories.

# PARAMETERS SECTION: User-configurable inputs for the template
Parameters:
  GitLabNamespaces:
    Type: CommaDelimitedList
    Default: "pjv93,another-group"
    Description: >
      A comma-separated list of GitLab namespaces (groups or users).
      - Examples:
        - Single namespace: 'pjv93'
        - Multiple namespaces: 'pjv93,another-group'.
      - IMPORTANT: Ensure the namespaces match your GitLab project paths.

  RepositoriesPerNamespace:
    Type: String
    Default: "repo1,repo2|*"
    Description: >
      Pipe-separated repository lists corresponding to each namespace in the 'GitLabNamespaces' parameter.
      - Format: 'repo1,repo2|repo3,repo4' (repositories for each namespace separated by commas, namespaces separated by pipes '|').
      - To allow access to all repositories for a namespace, use '*':
        - Example for all repositories in 'pjv93': '*'.
        - Example for mixed access: 'repo1,repo2|*'.
      - IMPORTANT: Make sure the repositories exist within the specified namespaces.

  S3BucketName:
    Type: String
    Default: "iampjv.co"
    Description: >
      The name of the S3 bucket to grant access to GitLab CI/CD pipelines.
      - IMPORTANT: Ensure the bucket name matches your existing S3 bucket in AWS.

# RESOURCES SECTION: AWS resources created by the template
Resources:
  # Lambda function to process namespaces and repositories into IAM-compatible patterns
  RepoListProcessor:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import cfnresponse
          
          def handler(event, context):
              try:
                  if event['RequestType'] in ['Create', 'Update']:
                      # Parse input parameters
                      namespaces = event['ResourceProperties']['GitLabNamespaces'].split(',')
                      repos_per_namespace = event['ResourceProperties']['RepositoriesPerNamespace'].split('|')

                      # Validate lengths
                      if len(namespaces) != len(repos_per_namespace):
                          raise ValueError("Mismatch between number of namespaces and repositories-per-namespace.")

                      # Build repository patterns
                      repo_patterns = []
                      for namespace, repos in zip(namespaces, repos_per_namespace):
                          if repos == '*':
                              repo_patterns.append(f"project_path:{namespace}/*")
                          else:
                              for repo in repos.split(','):
                                  repo_patterns.append(f"project_path:{namespace}/{repo}")

                      # Send the formatted patterns back to CloudFormation
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {'RepoPatterns': ','.join(repo_patterns)})
                  else:
                      # Handle Delete or no-op
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  print(f"Error: {e}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})
      Runtime: python3.9
      Timeout: 30

  # IAM Role for the Lambda function to enable execution
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Custom resource to dynamically generate repository patterns
  RepoListCustomResource:
    Type: Custom::RepoList
    Properties:
      ServiceToken: !GetAtt RepoListProcessor.Arn
      GitLabNamespaces: !Join [ ",", !Ref GitLabNamespaces ]
      RepositoriesPerNamespace: !Ref RepositoriesPerNamespace

  # GitLab OIDC Provider to establish trust with AWS
  GitLabOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: "https://gitlab.com"
      ClientIdList:
        - "sts.amazonaws.com"  # AWS STS service is the client
      ThumbprintList:
        - "9e99a48a9960b14926bb7f3b6bfa10796a8aef5e"  # GitLab OIDC thumbprint

  # IAM Role for GitLab CI/CD pipelines
  GitLabActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "GitLab_Actions_Role_${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/gitlab.com"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              # Match audience claim in OIDC token
              StringEquals:
                "gitlab.com:aud": "sts.amazonaws.com"
              # Restrict access to dynamically generated project paths
              StringLike:
                "gitlab.com:sub": !Split [ ",", !GetAtt RepoListCustomResource.RepoPatterns ]

  # IAM Policy to grant permissions to the S3 bucket
  GitLabActionsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-GitLabActionsPolicy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Bucket-level permissions
          - Sid: AllowS3BucketActions
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}"
          # Object-level permissions
          - Sid: AllowS3ObjectActions
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}/*"
      Roles:
        - !Ref GitLabActionsRole  # Attach policy to GitLabActionsRole

# OUTPUTS SECTION: Useful information from the stack
Outputs:
  GitLabActionsRoleArn:
    Description: The ARN of the IAM Role for GitLab CI/CD
    Value: !GetAtt GitLabActionsRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GitLabActionsRoleArn"

  GitLabOidcProviderArn:
    Description: The ARN of the GitLab OIDC Provider
    Value: !GetAtt GitLabOidcProvider.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GitLabOidcProviderArn"
